import { join } from 'node:path';
import { ensureDir, pathExists, removePath, writeTextFile } from '../utils/fs';
import { clientDir, clientEnvPath, clientEnvPs1Path } from '../core/paths';
import { AnyPickError } from '../utils/errors';

/**
 * Write portable env files for a client under ~/.anypick/clients/<id>/.
 * Always written so users can `source` them; adapters may also write native config.
 */
export async function writeClientEnvFiles(
  anypickRoot: string,
  clientId: string,
  env: Record<string, string>,
): Promise<string[]> {
  for (const key of Object.keys(env)) {
    // These names are emitted into executable shell and PowerShell files.
    // Profile overlay keys are user/config supplied, so never let one become
    // syntax (for example `X; Invoke-Expression ...`).
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      throw new AnyPickError(`Invalid environment variable name: ${JSON.stringify(key)}.`, {
        code: 'CLIENT_CONFIG_INVALID',
      });
    }
  }
  await ensureDir(clientDir(anypickRoot, clientId));
  const shPath = clientEnvPath(anypickRoot, clientId);
  const ps1Path = clientEnvPs1Path(anypickRoot, clientId);

  const shLines = [
    `# Generated by anypick — do not edit by hand`,
    `# source ${shPath}`,
    ...Object.entries(env).map(([k, v]) => `export ${k}=${shellQuote(v)}`),
    '',
  ];
  const ps1Lines = [
    `# Generated by anypick — do not edit by hand`,
    ...Object.entries(env).map(([k, v]) => `$env:${k} = ${psQuote(v)}`),
    '',
  ];

  await writeTextFile(shPath, shLines.join('\n'), 0o600);
  await writeTextFile(ps1Path, ps1Lines.join('\n'), 0o600);
  return [shPath, ps1Path];
}

export async function removeClientEnvFiles(anypickRoot: string, clientId: string): Promise<void> {
  for (const path of [
    clientEnvPath(anypickRoot, clientId),
    clientEnvPs1Path(anypickRoot, clientId),
  ]) {
    if (await pathExists(path)) {
      await removePath(path);
    }
  }
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Marker used in JSON settings to track anypick-managed env keys. */
export const ANYPICK_MANAGED_KEY = '_anypickManaged';

export function managedMarker(keys: string[]): {
  keys: string[];
  updatedAt: string;
} {
  return { keys, updatedAt: new Date().toISOString() };
}

export function clientHomeConfigDir(clientId: string, home: string): string {
  // Client ids already match their home-config directory names (`.claude`,
  // `.codex`, …). Do not special-case built-ins here — third-party clients
  // would inherit the wrong path.
  return join(home, `.${clientId}`);
}
